import { presetForms } from "@julr/unocss-preset-forms";
import {
	defineConfig,
	presetIcons,
	presetWind3,
	transformerDirectives,
	transformerVariantGroup,
} from "unocss";

export default defineConfig({
	content: {
		filesystem: ["app/**/*.{html,js,ts,jsx,tsx,vue,svelte,astro}"],
	},
	presets: [presetWind3({ dark: "class" }), presetIcons(), presetForms()],
	transformers: [transformerDirectives(), transformerVariantGroup()],
	safelist: [
		"text-xs",
		"text-gray-500",
		"i-solar-medical-kit-bold",
		"i-solar-fire-bold",
		"i-solar-shield-bold",
		"i-solar-settings-bold",
		"i-solar-waterdrop-bold",
		"i-solar-danger-triangle-bold",
		"i-solar-widget-6-bold",
		"bg-red-50",
		"text-red-700",
		"border-red-200",
		"dark:bg-red-900/70",
		"dark:text-red-300",
		"dark:border-red-700/50",
		"bg-orange-50",
		"text-orange-700",
		"border-orange-200",
		"dark:bg-orange-900/70",
		"dark:text-orange-300",
		"dark:border-orange-700/50",
		"bg-blue-50",
		"text-blue-700",
		"border-blue-200",
		"dark:bg-blue-900/70",
		"dark:text-blue-300",
		"dark:border-blue-700/50",
		"bg-cyan-50",
		"text-cyan-700",
		"border-cyan-200",
		"dark:bg-cyan-900/70",
		"dark:text-cyan-300",
		"dark:border-cyan-700/50",
		"bg-amber-50",
		"text-amber-700",
		"border-amber-200",
		"dark:bg-amber-900/70",
		"dark:text-amber-300",
		"dark:border-amber-700/50",
		"bg-violet-50",
		"text-violet-700",
		"border-violet-200",
		"dark:bg-violet-900/70",
		"dark:text-violet-300",
		"dark:border-violet-700/50",
		"bg-emerald-50",
		"text-emerald-700",
		"border-emerald-200",
		"dark:bg-emerald-900/70",
		"dark:text-emerald-300",
		"dark:border-emerald-700/50",
		"bg-rose-500/35",
		"animate-ping",
		"size-9",
		"size-11",
		"size-5",
		"bg-zinc-100",
		"text-zinc-600",
		"border-zinc-200",
		"dark:bg-neutral-800",
		"dark:text-zinc-300",
		"dark:border-neutral-700",
	],
});
