/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents (paginated) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description ISO date-time cursor for pagination */
                    cursor?: string;
                    /** @description Filter by status (repeatable) */
                    status?: components["schemas"]["Status"];
                    /** @description Filter by incident type code (repeatable) */
                    type?: string;
                    /** @description Filter by createdAt >= from (ISO date-time) */
                    from?: string;
                    /** @description Filter by createdAt <= to (ISO date-time) */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated incident list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new incident
         * @description Reporter ID is read from the `x-user-id` request header injected by the API gateway.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateIncidentRequest"];
                };
            };
            responses: {
                /** @description Created incident */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Incident"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List open incidents
         * @description Returns up to 200 incidents with status created, dispatched, or in_progress.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Open incidents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentItemsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find active incidents near a GPS coordinate
         * @description Returns up to 50 active (non-resolved, non-cancelled) incidents within the given radius, ordered by distance. Intended for dispatch situational awareness.
         */
        get: {
            parameters: {
                query: {
                    lat: number;
                    lng: number;
                    /** @description Search radius in km (max 500) */
                    radius?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nearby incidents with distance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NearbyIncidentsResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get incident by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Incident found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Incident"];
                    };
                };
                /** @description Missing ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetailError"];
                    };
                };
                /** @description Incident not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetailError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update incident status */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateStatusRequest"];
                };
            };
            responses: {
                /** @description Updated incident */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Incident"];
                    };
                };
                /** @description Validation error or missing ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetailError"];
                    };
                };
                /** @description Incident not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetailError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign or unassign an operator to an incident */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignRequest"];
                };
            };
            responses: {
                /** @description Updated incident */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Incident"];
                    };
                };
                /** @description Validation error or missing ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetailError"];
                    };
                };
                /** @description Incident not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetailError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenAPI document */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Swagger UI */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Swagger UI */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Status: "created" | "dispatched" | "in_progress" | "resolved" | "cancelled";
        /** @enum {string} */
        ResponderType: "police" | "fire" | "hospital";
        /** @enum {string} */
        ResponderStatus: "available" | "dispatched" | "off_duty";
        /** @enum {string} */
        PriorityLevel: "low" | "medium" | "high";
        IncidentLocation: {
            address: string;
            /** @description [lat, lng] */
            center: number[];
            radius: number;
        };
        IncidentType: {
            code: string;
            category?: string;
        };
        IncidentPriority: {
            level: components["schemas"]["PriorityLevel"];
            score?: number;
            escalationMins?: number;
        };
        IncidentMetadata: {
            callerName: string;
            callerContact: string;
            notes?: string;
        };
        Incident: {
            id: number;
            type: components["schemas"]["IncidentType"];
            description?: string | null;
            location: components["schemas"]["IncidentLocation"];
            priority: components["schemas"]["IncidentPriority"];
            metadata?: components["schemas"]["IncidentMetadata"];
            status: components["schemas"]["Status"];
            reporterId?: string | null;
            operatorId?: string | null;
            version: number;
            /** Format: date-time */
            dispatchedAt?: string | null;
            /** Format: date-time */
            resolvedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NearbyIncident: components["schemas"]["Incident"] & {
            distance_km: number;
        };
        Responder: {
            id: number;
            name: string;
            type: components["schemas"]["ResponderType"];
            status: components["schemas"]["ResponderStatus"];
            location?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateIncidentRequest: {
            type: components["schemas"]["IncidentType"];
            description?: string;
            location: components["schemas"]["IncidentLocation"];
            priority: components["schemas"]["IncidentPriority"];
            metadata?: components["schemas"]["IncidentMetadata"];
        };
        UpdateStatusRequest: {
            status: components["schemas"]["Status"];
        };
        AssignRequest: {
            operatorId: string | null;
        };
        IncidentListResponse: {
            items: components["schemas"]["Incident"][];
            limit: number;
            /** Format: date-time */
            nextCursor: string | null;
        };
        IncidentItemsResponse: {
            items: components["schemas"]["Incident"][];
        };
        NearbyIncidentsResponse: {
            items: components["schemas"]["NearbyIncident"][];
        };
        RespondersResponse: {
            items: components["schemas"]["Responder"][];
        };
        DetailError: {
            detail: string;
        };
        ValidationError: {
            detail: string;
            errors: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
