/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/dispatches/active": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List active dispatches */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Active dispatch records */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Dispatch"][];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/dispatches/{id}/arrive": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Mark dispatch as arrived */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Dispatch updated to arrived */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Dispatch"];
					};
				};
				/** @description Invalid dispatch id */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
				/** @description Dispatch not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/vehicles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List vehicles with latest location */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Vehicles */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Vehicle"][];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/stations": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List stations */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Stations */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Station"][];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/stations/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register a station and bootstrap responders */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["RegisterStationRequest"];
				};
			};
			responses: {
				/** @description Station created and responders provisioned */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["StationBootstrapResponse"];
					};
				};
				/** @description Validation failed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationError"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/stations/seed": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Seed demo stations and responders */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["SeedStationsRequest"];
				};
			};
			responses: {
				/** @description Seed completed */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["SeedStationsResponse"];
					};
				};
				/** @description Validation failed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationError"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/vehicles/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register a new vehicle */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["RegisterVehicleRequest"];
				};
			};
			responses: {
				/** @description Vehicle registered */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Vehicle"];
					};
				};
				/** @description Validation failed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationError"];
					};
				};
				/** @description Station not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
				/** @description Vehicle callSign already exists */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/vehicles/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a vehicle by id */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Vehicle record */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Vehicle"];
					};
				};
				/** @description Invalid vehicle id */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
				/** @description Vehicle not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/vehicles/{id}/location": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List historical vehicle locations */
		get: {
			parameters: {
				query?: {
					limit?: number;
					/** @description Location row id cursor for pagination */
					cursor?: number;
					/** @description ISO date-time lower bound for recordedAt */
					from?: string;
					/** @description ISO date-time upper bound for recordedAt */
					to?: string;
				};
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Location history */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["VehicleLocationListResponse"];
					};
				};
				/** @description Invalid path/query parameter */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
			};
		};
		put?: never;
		/** Add a vehicle location point */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["UpdateVehicleLocationRequest"];
				};
			};
			responses: {
				/** @description Vehicle location created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["VehicleLocation"];
					};
				};
				/** @description Validation failed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationError"];
					};
				};
				/** @description Vehicle not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/drivers/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register a driver and link to a vehicle */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["RegisterDriverRequest"];
				};
			};
			responses: {
				/** @description Driver registered */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Driver"];
					};
				};
				/** @description Validation failed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationError"];
					};
				};
				/** @description Vehicle not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
				/** @description Vehicle already has a driver */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/drivers/{id}/location": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Add a driver location point */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["UpdateDriverLocationRequest"];
				};
			};
			responses: {
				/** @description Driver location created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							id: number;
							driverId: number;
							lat: number;
							lng: number;
							/** Format: date-time */
							recordedAt: string;
						};
					};
				};
				/** @description Validation failed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationError"];
					};
				};
				/** @description Driver not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/hospital/{id}/capacity": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update hospital capacity figures */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number;
				};
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["UpdateHospitalCapacityRequest"];
				};
			};
			responses: {
				/** @description Hospital capacity updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Hospital"];
					};
				};
				/** @description Missing or invalid input */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json":
							| components["schemas"]["DetailError"]
							| components["schemas"]["ValidationError"];
					};
				};
				/** @description Hospital not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DetailError"];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/tracking/live": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Stream live tracking updates via Server-Sent Events */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description SSE stream connection */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/event-stream": string;
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/doc": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get OpenAPI document */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OpenAPI JSON */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/ui": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Swagger UI */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Swagger UI */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** @enum {string} */
		VehicleType: "ambulance" | "fire_truck" | "police_car" | "motorcycle";
		/** @enum {string} */
		VehicleStatus:
			| "available"
			| "dispatched"
			| "en_route"
			| "on_scene"
			| "returning"
			| "offline";
		/** @enum {string} */
		DispatchStatus: "active" | "arrived" | "cleared";
		/** @enum {string} */
		StationType: "ambulance" | "fire" | "police";
		ResourceLocation: {
			address: string;
			lat: number;
			lng: number;
		};
		Station: {
			id: number;
			name: string;
			type: components["schemas"]["StationType"];
			location: components["schemas"]["ResourceLocation"];
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		Driver: {
			id: number;
			name: string;
			phone?: string | null;
			vehicleId?: number | null;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		VehicleLocation: {
			id: number;
			vehicleId: number;
			lat: number;
			lng: number;
			speed?: number | null;
			heading?: number | null;
			/** Format: date-time */
			recordedAt: string;
		};
		Vehicle: {
			id: number;
			callSign: string;
			type: components["schemas"]["VehicleType"];
			status: components["schemas"]["VehicleStatus"];
			stationId: number;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
			station?: components["schemas"]["Station"];
			driver?: components["schemas"]["Driver"] | null;
			locations?: components["schemas"]["VehicleLocation"][];
		};
		Dispatch: {
			id: number;
			incidentId: string;
			vehicleId: number;
			status: components["schemas"]["DispatchStatus"];
			/** Format: date-time */
			dispatchedAt: string;
			/** Format: date-time */
			arrivedAt?: string | null;
			/** Format: date-time */
			clearedAt?: string | null;
			vehicle?: components["schemas"]["Vehicle"];
		};
		Hospital: {
			id: number;
			name: string;
			location: components["schemas"]["ResourceLocation"];
			totalBeds: number;
			availableBeds: number;
			totalAmbulances: number;
			availableAmbulances: number;
			/** Format: date-time */
			updatedAt: string;
		};
		RegisterVehicleRequest: {
			callSign: string;
			type: components["schemas"]["VehicleType"];
			stationId: number;
			status?: components["schemas"]["VehicleStatus"];
		};
		UpdateVehicleLocationRequest: {
			lat: number;
			lng: number;
			speed?: number | null;
			heading?: number | null;
			/** Format: date-time */
			recordedAt?: string;
		};
		RegisterDriverRequest: {
			name: string;
			phone?: string;
			vehicleId: number;
		};
		UpdateDriverLocationRequest: {
			lat: number;
			lng: number;
			/** Format: date-time */
			recordedAt?: string;
		};
		UpdateHospitalCapacityRequest: {
			availableBeds?: number;
			totalBeds?: number;
			availableAmbulances?: number;
			totalAmbulances?: number;
		};
		RegisterStationRequest: {
			name: string;
			type: components["schemas"]["StationType"];
			location: components["schemas"]["ResourceLocation"];
			/**
			 * @default 4
			 * @enum {integer}
			 */
			respondersCount: 3 | 4;
		};
		SeedStationsRequest: {
			/** @default true */
			reset: boolean;
			/**
			 * @default full
			 * @enum {string}
			 */
			profile: "small" | "full";
		};
		StationBootstrapResponse: {
			station: components["schemas"]["Station"];
			respondersCount: number;
			vehicleType: components["schemas"]["VehicleType"];
			vehicles: {
				id: number;
				callSign: string;
				lat: number;
				lng: number;
			}[];
		};
		SeedStationsResponse: {
			profile: "small" | "full";
			reset: boolean;
			stationsCreated: number;
			vehiclesCreated: number;
			respondersCreated: number;
			stations: {
				id: number;
				name: string;
				type: components["schemas"]["StationType"];
				respondersCount: number;
				vehicleType: components["schemas"]["VehicleType"];
			}[];
		};
		VehicleLocationListResponse: {
			items: components["schemas"]["VehicleLocation"][];
			nextCursor: number | null;
		};
		ValidationError: {
			detail:
				| string
				| {
						[key: string]: unknown;
				  };
			errors?: {
				[key: string]: unknown;
			};
		};
		DetailError: {
			detail: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
