/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/response-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Average response times
         * @description Returns average response times per emergency service.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Inclusive start of range in ISO date-time format. */
                    from?: components["parameters"]["FromQuery"];
                    /** @description Inclusive end of range in ISO date-time format. */
                    to?: components["parameters"]["ToQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Response-time analytics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResponseTimesResponse"];
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents-by-region": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incidents by region and type */
        get: {
            parameters: {
                query?: {
                    /** @description Inclusive start of range in ISO date-time format. */
                    from?: components["parameters"]["FromQuery"];
                    /** @description Inclusive end of range in ISO date-time format. */
                    to?: components["parameters"]["ToQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Incident aggregation grouped by region and incident type */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentsByRegionResponse"];
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-utilization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resource utilization analytics
         * @description Returns hospital bed usage and top deployed responders grouped by emergency service.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Inclusive start of range in ISO date-time format. */
                    from?: components["parameters"]["FromQuery"];
                    /** @description Inclusive end of range in ISO date-time format. */
                    to?: components["parameters"]["ToQuery"];
                    /** @description How many responders per emergency service to return. */
                    top?: components["parameters"]["TopQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resource utilization metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceUtilizationResponse"];
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Range: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
        };
        ResponseTimesOverall: {
            avgMinutes: number | null;
            totalDispatches: number;
            totalArrived: number;
        };
        ResponseTimesByServiceItem: {
            /** @enum {string} */
            emergencyService: "ambulance" | "fire" | "police";
            avgMinutes: number | null;
            p50Minutes: number | null;
            p95Minutes: number | null;
            totalDispatches: number;
            totalArrived: number;
            arrivalRate: number | null;
        };
        ResponseTimesResponse: {
            range: components["schemas"]["Range"];
            overall: components["schemas"]["ResponseTimesOverall"];
            byService: components["schemas"]["ResponseTimesByServiceItem"][];
        };
        IncidentsByRegionItem: {
            region: string;
            incidentType: string;
            count: number;
        };
        IncidentsByRegionResponse: {
            range: components["schemas"]["Range"];
            totalIncidents: number;
            breakdown: components["schemas"]["IncidentsByRegionItem"][];
        };
        BedUsage: {
            totalBeds: number;
            availableBeds: number;
            usedBeds: number;
            usageRatePercent: number | null;
        };
        TopResponder: {
            responderId: string;
            responderName: string | null;
            deployments: number;
        };
        ResourceUtilizationResponse: {
            range: components["schemas"]["Range"];
            hospitalsConsidered: number;
            bedUsage: components["schemas"]["BedUsage"];
            topRespondersByService: {
                [key: string]: components["schemas"]["TopResponder"][];
            };
        };
        ErrorResponse: {
            detail: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Inclusive start of range in ISO date-time format. */
        FromQuery: string;
        /** @description Inclusive end of range in ISO date-time format. */
        ToQuery: string;
        /** @description How many responders per emergency service to return. */
        TopQuery: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
